### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by johnamcruz** [windy1/google-places-api-java#19]
Hello Guys,

I was wondering if you guys seen this error before. I am trying to integrate this library into my android app. It compiles without any problems but crashes when i run the app. The error is below.

Thanks!

John

=====================
Process: com.johamcruz.Balln, PID: 4118
    java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/message/BasicLineFormatter; in class Lorg/apache/http/message/BasicLineFormatter; or its superclasses (declaration of 'org.apache.http.message.BasicLineFormatter' appears in /system/framework/ext.jar)
            at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
            at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
            at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
            at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
            at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
            at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:493)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
            at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
            at se.walkercrou.places.DefaultRequestHandler.<init>(DefaultRequestHandler.java:18)
            at se.walkercrou.places.DefaultRequestHandler.<init>(DefaultRequestHandler.java:34)
            at se.walkercrou.places.GooglePlaces.<init>(GooglePlaces.java:39)
            at com.johamcruz.Balln.Activities.NearbyCourtsActivity$1.run(NearbyCourtsActivity.java:45)
            at java.lang.Thread.run(Thread.java:818)
02-28 22:31:42.220    4118-4127/com.johamcruz.Balln E/System﹕ Uncaught exception thrown by finalizer
02-28 22:31:42.221    4118-4127/com.johamcruz.Balln E/System﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.atomic.AtomicBoolean.compareAndSet(boolean, boolean)' on a null object reference
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.shutdown(PoolingHttpClientConnectionManager.java:349)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.finalize(PoolingHttpClientConnectionManager.java:172)
            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
            at java.lang.Thread.run(Thread.java:818)

**Comment by johnamcruz** [comment]
I figured out the solution. I created my own RequestHandler that uses the default http client.

**Comment by windy1** [comment]
This can be fixed by adding the following dependency to your gradle file. 

```java
dependencies {
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
}
```

No custom RequestHandler required.
