### ISSUE TITLE
MAXIMUM_RESULTS for Radar search

### ISSUE THREAD

**Issue by GGrasso** [windy1/google-places-api-java#21]
Radar search returns 200 results at once but the result is treated like 60 Result per page, therefore only the first 20 places are retrieved.

**Comment by eamonter** [comment]
For me it just doesn't work. getNearbyPlaces works fine: 
client.getNearbyPlaces(-37.801869, 144.987198, 500, 3) 
but getPlacesByRadar does not (same inputs)
client.getPlacesByRadar(-37.801869, 144.987198, 500, 3)

It throws the following error:

Exception in thread "main" se.walkercrou.places.exception.GooglePlacesException: se.walkercrou.places.exception.InvalidRequestException: INVALID_REQUEST
	at se.walkercrou.places.GooglePlaces.getPlacesByRadar(GooglePlaces.java:244)
	at se.walkercrou.places.GooglePlaces.getPlacesByRadar(GooglePlaces.java:250)
	at laundry.Laundry.main(Laundry.java:27)
Caused by: se.walkercrou.places.exception.InvalidRequestException: INVALID_REQUEST
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at se.walkercrou.places.exception.GooglePlacesException.parse(GooglePlacesException.java:87)
	at se.walkercrou.places.GooglePlaces.checkStatus(GooglePlaces.java:68)
	at se.walkercrou.places.GooglePlaces.parse(GooglePlaces.java:88)
	at se.walkercrou.places.GooglePlaces.getPlaces(GooglePlaces.java:396)
	at se.walkercrou.places.GooglePlaces.getPlacesByRadar(GooglePlaces.java:242)
	... 2 more
Java Result: 1
BUILD SUCCESSFUL (total time: 1 second)

**Comment by 0x3333** [comment]
Same here, I'll create a PR.

**Comment by 0x3333** [comment]
How is the release schedule? Do you plan to release version 2.1.3 anytime soon?

**Comment by windy1** [comment]
Release schedule is basically whenever I feel like enough has changed to warrant a release haha. v2.1.6 is now available in the release section and should be available on Maven Central shortly!

**Comment by 0x3333** [comment]
hahahah fair enough! Thanks!

**Comment by tawandabrandon** [comment]
Hi! I am getting this error,,how can I get around it?



Exception in thread "main" se.walkercrou.places.exception.GooglePlacesException: se.walkercrou.places.exception.InvalidRequestException: INVALID_REQUEST
	at se.walkercrou.places.GooglePlaces.getPlacesByRadar(GooglePlaces.java:272)
	at longstreet.finder.getRadar(finder.java:45)
	at longstreet.Longstreet.main(Longstreet.java:28)
Caused by: se.walkercrou.places.exception.InvalidRequestException: INVALID_REQUEST
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at se.walkercrou.places.exception.GooglePlacesException.parse(GooglePlacesException.java:87)
	at se.walkercrou.places.GooglePlaces.checkStatus(GooglePlaces.java:77)
	at se.walkercrou.places.GooglePlaces.parseRadar(GooglePlaces.java:119)
	at se.walkercrou.places.GooglePlaces.getRadarPlaces(GooglePlaces.java:444)
	at se.walkercrou.places.GooglePlaces.getPlacesByRadar(GooglePlaces.java:270)
	... 2 more
C:\Users\Oktane\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 2 seconds)
