### ISSUE TITLE
FATAL EXCEPTION: main     java.lang.NoSuchFieldError: org.apache.http.message.BasicLineFormatter.INSTANCE

### ISSUE THREAD

**Issue by vincentderidder** [windy1/google-places-api-java#29]
I stumble on this error when creating a new google places object.

**Comment by windy1** [comment]
Can you post the full error and your gradle file (if working on android) please?

**Comment by vincentderidder** [comment]
I just used the .jar file so i did'nt changed anything there. 

Errorlog:
05-08 15:52:51.036  11873-11873/be.vincentderidder.flymiles E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchFieldError: org.apache.http.message.BasicLineFormatter.INSTANCE
            at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
            at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
            at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
            at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
            at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
            at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:493)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
            at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
            at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
            at se.walkercrou.places.DefaultRequestHandler.<init>(DefaultRequestHandler.java:18)
            at se.walkercrou.places.DefaultRequestHandler.<init>(DefaultRequestHandler.java:34)
            at se.walkercrou.places.GooglePlaces.<init>(GooglePlaces.java:39)
            at be.vincentderidder.flymiles.NewRouteFragment.onCreate(NewRouteFragment.java:38)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5143)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2239)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
            at android.app.ActivityThread.access$600(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5225)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at dalvik.system.NativeStart.main(Native Method)

gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "be.vincentderidder.flymiles"
        minSdkVersion 18
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.google.android.gms:play-services:7.3.0'


}

**Comment by windy1** [comment]
Yeah don't use the JAR file for Android, use the maven dependency. You also need to include the apache-http compat lib (as it says in the README). So something like this:

```java
repositories {
    mavenCentral()
}

dependencies {
    compile 'se.walkercrou:google-places-api-java:2.1.2'
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
}
```

I'm not trying to single you out @vincentderidder but rather speak to everyone who might see this: Please look into errors by reading the README, looking at old issues, etc before creating a new issue. I get this identical issue almost every week now. Thanks.
